apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense1
  # labels of deployment resource
  labels:
    app: frontend
    tier: frontend
    project: expense1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      project: expense1
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        project: expense1
    spec:
      containers:
      - name: nginx
        image: nagaleelachandrala/frontend:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense1
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: frontend
    tier: web
    project: expense1
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80