apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense1
  # labels of deployment resource
  labels:
    app: mysql
    tier: mysql
    project: expense1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense1
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense1
    spec:
      containers:
      - name: nginx
        image: nagaleelachandrala/mysql:1.0.0
---
# kind: Service
# apiVersion: v1
# metadata:
#   name: mysql
#   namespace: expense
# spec:
#   selector: # labels are used as selectors
#     app: mysql
#     tier: mysql
#     project: expense
#   ports:
#   - protocol: TCP
#     port: 3306 # service port
#     targetPort: 3306